// JsFromRoutes CacheKey eade040c162542808939a896a29d917a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  new: definePathHelper('get', '/login'),
  create: definePathHelper('post', '/login'),
  destroy: definePathHelper('delete', '/logout'),
}
