// JsFromRoutes CacheKey c972eaa989a54bedb84625270e724a89
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  destroy: definePathHelper('delete', '/contacts/:id'),
  update: definePathHelper('patch', '/contacts/:id'),
  restore: definePathHelper('put', '/contacts/:id/restore'),
  list: definePathHelper('get', '/contacts'),
  create: definePathHelper('post', '/contacts'),
  new: definePathHelper('get', '/contacts/new'),
  edit: definePathHelper('get', '/contacts/:id/edit'),
}
