// JsFromRoutes CacheKey 56256b4de5d51f00dbf4bfe4fff9b4b6
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  exampleException: definePathHelper('get', '/error-500'),
  list: definePathHelper('get', '/'),
}
