// JsFromRoutes CacheKey 9e90d661816fc15c10fccfe00fd901eb
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  list: definePathHelper('get', '/reports'),
}
