// JsFromRoutes CacheKey e6f496be19c3519a9913f0a5d90ec976
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/inertia'

export default {
  restore: definePathHelper('put', '/users/:id/restore'),
  list: definePathHelper('get', '/users'),
  create: definePathHelper('post', '/users'),
  new: definePathHelper('get', '/users/new'),
  edit: definePathHelper('get', '/users/:id/edit'),
  update: definePathHelper('patch', '/users/:id'),
  destroy: definePathHelper('delete', '/users/:id'),
}
